version: '3.7'

services:
  mysql:
    container_name: adm_alt_bank_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=alt_bank
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - adm_alt_bank_network

networks:
  adm_alt_bank_network: